version: '3'

services:
  funding-mysql:
    image: mysql
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: funding
      MYSQL_ROOT_PASSWORD: root